version: '3.8'

services:
  auth1:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm i && node dist/server/auth.js"
    environment:
      - GRPC_PORT=10001
    ports:
      - "10001:10001"

  auth2:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm i && node dist/server/auth.js"
    environment:
      - GRPC_PORT=10002
    ports:
      - "10002:10002"

  auth-lb:
    image: nginx:latest
    ports:
      - "10000:10000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth1
      - auth2

  gateway1:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm i && node dist/server/gateway.js"
    environment:
      - AUTH_LB=auth-lb:10000
      - WS_PORT=4001
    ports:
      - "4001:4001"

  gateway2:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm i && node dist/server/gateway.js"
    environment:
      - AUTH_LB=auth-lb:10000
      - WS_PORT=4002
    ports:
      - "4002:4002"

  gateway-lb:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway1
      - gateway2
